# Generated by Django 5.0.1 on 2024-01-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_demand_geography_skill_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
