# Generated by Django 5.0.1 on 2024-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_delete_todoitem_remove_demand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SK', 'Skills'), ('DM', 'Demand'), ('GR', 'Geography')], max_length=2)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
