# Generated by Django 5.0.1 on 2024-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_image_delete_demand_delete_geography_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SK', 'Skills'), ('DM', 'Demand'), ('GR', 'Geography')], max_length=2)),
                ('csv_file', models.FileField(upload_to='csvs/')),
            ],
        ),
    ]
